### ISSUE TITLE
All shards failed when using "!=" operator for _id field starting with "-"

### ISSUE THREAD

**Issue by alirezaImani-f4L3e** [pdphilip/laravel-elasticsearch#13]
Hi philip
## Bug description
I have a problem using "!=" for comparing _id field with a value that starting with "-" .
please give me a solution to this problem . 

## To Reproduce
For Example :
```php
Audit::where('_id', '!=' , '-t9Z2o0BD6JyEaA0u_qU' )->get();

```
This code will cause an "query_shard_exception" with reson : "Failed to parse query" .

This _id have been automatically generated by elasticsearch.

**Comment by pdphilip** [comment]
Hi, which version of the package are you using? Please use the bug template, then I have more info to work with. 

I think I know where the issue lies, but will need to update test files for all the maintained packages

**Comment by pdphilip** [comment]
FYI, if you're still on 2.8 then updating to [v2.8.6](https://github.com/pdphilip/laravel-elasticsearch/releases/tag/v2.8.6) will fix this.
