### ISSUE TITLE
[Fixed] whereIn appears to be partial matching strings

### ISSUE THREAD

**Issue by davidmuggleton** [pdphilip/laravel-elasticsearch#17]
## Package version 
ex: v2.10.3  (NB!)

## Describe the bug

Say we have the following document:

```
{
     name: 'John Smith',
     jobs: ['AI Inc', 'Loops Services'] <!- keyword field
}
```

and we do a query

`Person::whereIn('jobs', ['AI', 'Loops'])->get();`

We would expect no results, however, the query IS matching with the example provided.

## Expected behavior

---
**Screenshots**:

**Component Versions (Paste in the `require` section from your composer.json file):**
```json
  "require": {
  
  },
```

**Additional context**:

**Comment by pdphilip** [comment]
Hey @davimug , seems to be getting hits on the text tokens.

Try:
```php
Person::whereIn('jobs.keyword', ['AI', 'Loops'])->get();
//or the equivalent:
Person::where('jobs.keyword', 'AI')->where('jobs.keyword', 'Loops')->get();
```

**Comment by davimug** [comment]
Hi @pdphilip , thanks for the response! I tried that and it doesn't seem to match with any documents at all, even the correct ones.

**Comment by pdphilip** [comment]
Strange, first try update to the latest version `v2.10.7` and see if it helps

Then, can you show me your mappings?
```php
Schema::getMappings('people');
```
I'm in the process of rebuilding the bridge that will use DSL queries directly, the `whereIn()` method will leverage Elasticsearch's terms query that will look for an exact match. This will be a major release `v3.x` - weeks away.

In the meantime, an equivalent query would be:
```php
Person::where('jobs', 'AI')->orWhere('jobs', 'Loops')->get();
```

Let me know where you land

**Comment by davimug** [comment]
Hi sorry for the late reply @pdphilip, amazing work! Will take a look
