### ISSUE TITLE
firstOrCreateWithOutRefresh or similar to improve speed

### ISSUE THREAD

**Issue by abkrim** [pdphilip/laravel-elasticsearch#19]
**Is your feature request related to a problem? Please describe.**
I use your package in an intensive system. After create a code to get for one index and migrate to another (local) based on docker I see a big problem with `Model::firstOrCreate()` 

First I thought it was the fault of the previous query to find out if the doc existed, and then creating it if it did not exist, was the cause.

But after doing a better job in the docker via no.

The time difference between using `Model::createWithoutRefresh($doc);` and `Model::firstOrCreate()` was overwhelming.

So I tried another approach.

```php
$exists = MOdel::where('log_id', $doc['log_id'])->exists();
if (! $exists) {
   WorkAnalyzer::createWithoutRefresh($doc);
}
```

And voila. Fly again.

I've reviewed the code to see if I could get around it, creating or extending it if necessary, to create something like `firstOrCreateWithoutRefresh()`, but I feel unable. So I gave up the idea.

And even with a little conversation, if you could advise me, I could try to create the PR, with the tests on the object.

Once again delighted with your package.

**Comment by pdphilip** [comment]
Hey @abkrim, to make sure I understand: You managed to solve the problem with the snippet you shared, but would like it to be a feature `firstOrCreateWithoutRefresh()` in the package?

**Comment by pdphilip** [comment]
Noted. Thanks for the suggestion. 

If I implment this then it will be in the next major (3.x) realease which I'm in the middle of building.

Will provide feedback here of the outcome.

**Comment by abkrim** [comment]
Looking forward to seeing it, and thus seeing the code to see how it was done. I'm learning a lot with your code.

Thank you very much for your work.

**Comment by pdphilip** [comment]
@abkrim - this feature has been added in v3, [docs](https://elasticsearch.pdphilip.com/saving-models#first-or-create-without-refresh)

Check it out!
