### ISSUE TITLE
Collection Cant Parse JSON or ARRAY

### ISSUE THREAD

**Issue by yuan8** [pdphilip/laravel-elasticsearch#3]
i will encode collection to json to strore vue js data
but when i was do that always error with message 

`json_decode(): Argument #1 ($json) must be of type string, array give`

`  dd(json_encode($data->items()));`
<img width="1392" alt="Screenshot 2023-06-14 at 17 34 29" src="https://github.com/pdphilip/laravel-elasticsearch/assets/9335377/a977d1d7-c8a4-429b-b82e-752ac1613c4f">

**Comment by pdphilip** [comment]
It's not clear to me what you're trying to do, and if this is an issue with plugin or how you're using Laravel. Laravel automatically returns JSON if you return data without a view, no need to encode.

If you're still stuck please give me more context (models, controllers & routes).

Cheers

**Comment by pdphilip** [comment]
Any feedback @yuan8 ? Happy to help, else will close this issue assuming you figured it out.

**Comment by yuan8** [comment]
sory i missing step. that problem only in my code. 
i used cast in my model to json data item. so wen i used model elastic its twice decode. 
thanks @pdphilip
