### ISSUE TITLE
Non latin words

### ISSUE THREAD

**Issue by Deviance-Dev** [pdphilip/laravel-elasticsearch#4]
Everything works fine, except for searching in Cyrillic, there is no output.

Although in Kibana everything works fine

**Comment by pdphilip** [comment]
Happy to have a look, but need more info:
- Which version of the plugin are you using? 
- Laravel and ES version?

Then please provide:
- The Laravel code you tried
- The query that worked in Kibana

**Comment by Deviance-Dev** [comment]
Plugin Version: 1.8x
Laravel 8x
ES 7.5.2

Code is working fine with english words, but not working with cyrillic.
`
$data = Post::where('text', 'like', $search)
                ->orderBy('date.keyword')
                ->paginate(15)
                ->appends(['search' => $search]);
`
Kibana request:

`
{
  "version": true,
  "size": 500,
  "sort": [
    {
      "_score": {
        "order": "desc"
      }
    }
  ],
  "_source": {
    "excludes": []
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [],
  "query": {
    "bool": {
      "must": [],
      "filter": [
        {
          "multi_match": {
            "type": "best_fields",
            "query": "президент",
            "lenient": true
          }
        }
      ],
      "should": [],
      "must_not": []
    }
  },
  "highlight": {
    "pre_tags": [
      "@kibana-highlighted-field@"
    ],
    "post_tags": [
      "@/kibana-highlighted-field@"
    ],
    "fields": {
      "*": {}
    },
    "fragment_size": 2147483647
  }
}
`

**Comment by pdphilip** [comment]
Hey @Deviance-Dev 

I think I was able to zero in on the issue here. Please update your plugin to 1.8.1 and try again: https://github.com/pdphilip/laravel-elasticsearch/releases/tag/v1.8.1

Let me know if that has fixed the issue so that I can port this updated to the other versions. Thanks!

**Comment by Deviance-Dev** [comment]
Oh, @pdphilip it's working now. Thank you very much for such great job :)
