### ISSUE TITLE
Nested / Dot notation whereExact Fails

### ISSUE THREAD

**Issue by use-the-fork** [pdphilip/laravel-elasticsearch#42]
## Describe the bug
When using `whereExact` with either a `queryNested` or by using dot notation a `ParameterException` occurs. This seems to be a direct result of the `parseRequiredKeywordMapping` helper in the Bridge.

## To Reproduce
Create a nested field mapping as part of the schema make sure it has a keyword mapping and then query in either of these fashions:

```php
       ConfiguredItem::queryNested('request', function ($query) use ($item) {
            $query->whereExact('item_number', $item['item_number']);
        })->toSql();
```

```php
       ConfiguredItem::whereExact('request.business_unit', $item['business_unit']))->toSql();
```

## Expected behavior
This should work as long as long as the field is mapped to a keyword field.

---
**Screenshots**:

![image](https://github.com/user-attachments/assets/54e200a9-d75b-4a19-8db7-8155e389d0d3)

![image](https://github.com/user-attachments/assets/03c93e35-1e36-4d99-8d4e-f848e8953633)

**Comment by pdphilip** [comment]
If you try:
```php
$query->whereExact('item_number.keyword', $item['item_number']);
``` 
and
```php
ConfiguredItem::whereExact('request.business_unit.keyword', $item['business_unit']))->get();
```
Then still the same issue?

Mapping order matters, so if you map the `$index->keyword` first and then `$index->text`; then `keyword` is used by default, and the field still remains `text` analysed for full-text searching. Just how ES works, they could really do that one better...

Let me know

**Comment by use-the-fork** [comment]
yes same issue. But let me try moving the mapping around I didn't think about that.

**Comment by use-the-fork** [comment]
No Same result. Here is my updated mapping:
![image](https://github.com/user-attachments/assets/29b67fae-b7ce-4118-8c44-46d1d42fd34e)

Here it is when I ask for mapping directly:
![image](https://github.com/user-attachments/assets/8d055683-2955-4248-862e-163bea9ab725)

and doing this:
```php
ConfiguredItem::whereExact('request.business_unit', $item['business_unit'])->toSql();
```
and this:
```php
onfiguredItem::queryNested('request', function ($query) use ($item) {
            $query->whereExact('business_unit', $item['business_unit']); //or comments.country
        })->toSql()
```

fails.
![image](https://github.com/user-attachments/assets/cb068c15-56e6-40db-9477-28b9d9f26c20)

**Comment by pdphilip** [comment]
Definitely a bug. I'll look into it. Thanks

**Comment by use-the-fork** [comment]
@pdphilip I fixed it. Raising a PR later today. It's because of the "." notation mostly
