### ISSUE TITLE
_parseFieldMap throws Exception with wildcard index.

### ISSUE THREAD

**Issue by gregory-lifhits-assaabloy** [pdphilip/laravel-elasticsearch#47]
## Package version 
ex: v4.4.0

## Describe the bug
When using a wildcard index in the model and a whereExact query the mapping lookup fails.
![image](https://github.com/user-attachments/assets/1ffea1c6-fcc8-4e95-b18b-dd4297b0644e)

## To Reproduce

Add a model with a wildcard index ie `protected $index = 'dam_documents_*';`

run a whereExact on that model ie:
`DamDocument::whereExact('meta.documentId', $this->documentId)->delete();`

## Expected behavior
The above should delete the documents but fails to retrive the mapping.

**Comment by pdphilip** [comment]
Yep, confirmed bug.  Pushed an update on https://github.com/pdphilip/laravel-elasticsearch/tree/dev-main - can you try?

**Comment by pdphilip** [comment]
Should be fixed in [v4.4.1](https://github.com/pdphilip/laravel-elasticsearch/releases/tag/v4.4.1)

Nice bug to squash
