### ISSUE TITLE
I think tahat your package is valid for latest version

### ISSUE THREAD

**Issue by abkrim** [pdphilip/laravel-elasticsearch#5]
Hi.

You have in composer.json `"elasticsearch/elasticsearch": "8.9"`

I think that your package is valid for 8.10.0

I don't see test but I think is valid.

**Comment by pdphilip** [comment]
Thanks, @abkrim - have updated the dependency along with several other upgrades/fixes

See https://github.com/pdphilip/laravel-elasticsearch/releases/tag/v2.10.2

**Comment by abkrim** [comment]
I'm happy to use your package, but I'd like to have access to the tests so I can upload some PR when I find something wrong @pdphilip

**Comment by pdphilip** [comment]
Sure thing @abkrim, I'll create a repo with the tests for Laravel 10 & the latest version and share it here with you.

**Comment by pdphilip** [comment]
@abkrim here are the tests: https://github.com/pdphilip/laravel-elasticsearch-tests - Would you like to contribute to the plugin by creating a PR with automated build tests from these? 

If there are any issues getting set up with the tests themselves please submit issues on that repo.

**Comment by abkrim** [comment]
I'm pretty busy, but I started using it in a project.

And if I see something that I can help, I will try to do the test and the PR corresponding to said test.

I like the package.
