### ISSUE TITLE
not working with docker

### ISSUE THREAD

**Issue by davoodf1995** [pdphilip/laravel-elasticsearch#7]
Hi, why not connect in docker 
my docker compose
`version: '3'
networks:
  default:
    ipam:
      config:
        - subnet: 172.16.0.0/16
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    logging:
      options:
        max-size: "5m"
        max-file: "10"
    volumes:
      - "./etc/nginx-stage/:/etc/nginx/conf.d/"
      - "./etc/nginx-config-stage/nginx.conf:/etc/nginx/nginx.conf"
      # - "./etc/ssl/:/etc/ssl/trust"

    environment:
      - NGINX_HOST=localhost

    command: /bin/sh -c "nginx -g 'daemon off;'"
    restart: always
    network_mode: host

  nginx-php-stage:
    image: yaroodf/nginx-php:8.1
    container_name: nginx-php-stage
    restart: always
    logging:
      options:
        max-size: "5m"
        max-file: "10"
    volumes:
      - "./etc/nginx-php-stage/php.ini:/etc/php/8.1/fpm/php.ini"
      - "./etc/nginx-php-stage/nginx.conf:/etc/nginx/sites-available/default"
      # - "./etc/ssl/:/etc/ssl/trust"
      - "./web/nginx-php-stage:/var/www/html"
      - "./etc/nginx-php-stage/cron/:/etc/cron.d/"
      - "./etc/nginx-php-stage/supervisord.conf:/etc/supervisor/supervisord.conf"

    networks:
      - default
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8082:8082"
      - "127.0.0.1:8083:8083"

    depends_on:
      - mysql
      - elasticsearch

  phpmyadmin:
    image: phpmyadmin
    logging:
      options:
        max-size: "5m"
        max-file: "10"
    container_name: phpmyadmin
    ports:
      - "127.0.0.1:8089:80"
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
    restart: always
    networks:
      - default
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.9
    logging:
      options:
        max-size: "5m"
        max-file: "10"
    container_name: mysql
    restart: always
    # env_file:
    #     - ".env"
    environment:
      # - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=admin
      # - MYSQL_USER=${MYSQL_USER}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "33061:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
      - ./etc/mysql/:/etc/mysql/conf.d/
    networks:
      - default

  redis:
    image: 'bitnami/redis:7.0.9'
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=t7FCdx9z6C9G
    # volumes:
    #   - '/path/to/redis-persistence:/bitnami'
    networks:
      - default
    container_name: redis
    restart: always

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - default
    # ports:
    #   - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.7.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - default
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601`

and my env in laravel is 
`ES_HOSTS="http://es-container:9200"`

**Comment by pdphilip** [comment]
Can you get to the ES instance from within Laravel? 
Try: `return Http::get('http://es-container:9200')->body();` 

If you can't, then try `http://localhost:9200`

If you can, then what does the Laravel error say?

**Comment by PandaTawer** [comment]
Hello!
I have a similar issue I cannot connect my Laravel to the ES within Docker.
ElasticSearch works fine when I approach it with http://localhost:9200 I can also request it with cURL from my terminal.
Also, I could set up Kibana so it should work within one docker network but all requests from Laravel fail with the same error.
`cURL error 7: Failed to connect to elasticsearch port 9200 after 0 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://elasticsearch:9200`
By the way, my ES container has the name elasticsearch.

**Comment by davoodf1995** [comment]
not working not connecting to docker with this package
I try with localhost 127.0.0.1 and es-container

**Comment by pdphilip** [comment]
Hey @davoodf1995 - I'm not sure where it's going wrong for you. Seems it's not a plugin issue, but rather a docker set-up problem; which falls outside the scope of this plugin.

I suggest posting on StackOverflow to get the community to help you out. 

I also have my docker ENV on Github, here: https://github.com/pdphilip/docker-LAMP-MR - maybe it helps
